//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Junio21.IF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudades
    {
        public int CiudadId { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> PaisId { get; set; }
    
        public virtual Paises Paises { get; set; }
    }
}
